/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define AHB1ENR 0x40023800U
#define GPIOD_EN 0x30U




#define GPIOD 0x40020C00U
#define GPIOD_MODER 0x00U
#define GPIOD_ODR 0x14U

int main(void)
{
    /* Loop forever */

	*((volatile uint32_t*)(AHB1ENR+GPIOD_EN)) |= (1 << 3); //BIT3 = ENABLE CLOCK
	*((volatile uint32_t*)(GPIOD+GPIOD_MODER)) |= (1 << 30); // SET OUTPUT PD15
	*((volatile uint32_t*)(GPIOD+GPIOD_MODER)) |= (1 << 28); // SET OUTPUT PD14




	for(;;){
		*((volatile uint32_t*)(GPIOD+GPIOD_ODR))|= (1 << 15); //SET PD15
		*((volatile uint32_t*)(GPIOD+GPIOD_ODR)) &= ~(1 << 14); //NOT SET PD14
		for(int i = 0; i < 100000; i++){};

		*((volatile uint32_t*)(GPIOD+GPIOD_ODR)) &= ~(1 << 15);
		*((volatile uint32_t*)(GPIOD+GPIOD_ODR))|= (1 << 14);
		for(int i = 0; i < 100000; i++){};
	}
}
